# Generated by Django 3.2 on 2022-11-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('subject', models.CharField(choices=[('national_languge', '国語'), ('math', '数学'), ('science', '理科'), ('society', '社会'), ('english', '英語')], max_length=100)),
                ('column3', models.CharField(max_length=30)),
            ],
        ),
    ]
