# Generated by Django 3.2 on 2022-12-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_card_column3'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='study',
            field=models.IntegerField(default=0),
        ),
    ]
