# Generated by Django 3.2 on 2022-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_card_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='study',
            field=models.IntegerField(),
        ),
    ]
