# Generated by Django 3.2 on 2022-12-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='study',
        ),
        migrations.AddField(
            model_name='card',
            name='review',
            field=models.IntegerField(default=0, verbose_name='復習回数,'),
        ),
        migrations.AddField(
            model_name='card',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='やり直し回数'),
        ),
    ]
