# Generated by Django 3.2 on 2022-12-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20221211_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='subject',
        ),
        migrations.AddField(
            model_name='card',
            name='answer_fake1',
            field=models.TextField(default='選択肢1'),
        ),
        migrations.AddField(
            model_name='card',
            name='answer_fake2',
            field=models.TextField(default='選択肢2'),
        ),
    ]
