# Generated by Django 3.2 on 2022-12-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20221212_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(default='問題'),
        ),
    ]
