# Generated by Django 3.2 on 2022-12-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_card_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(default='回答', max_length=100, verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer_fake1',
            field=models.CharField(default='選択肢1', max_length=100, verbose_name='選択肢1'),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer_fake2',
            field=models.CharField(default='選択肢2', max_length=100, verbose_name='選択肢2'),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(default='問題', verbose_name='問題'),
        ),
    ]
