# Generated by Django 3.2 on 2022-12-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20221212_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='review',
            field=models.IntegerField(verbose_name='復習回数,'),
        ),
        migrations.AlterField(
            model_name='card',
            name='review_count',
            field=models.IntegerField(verbose_name='やり直し回数'),
        ),
    ]
