# Generated by Django 3.2 on 2022-12-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20221213_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='review',
            field=models.IntegerField(verbose_name='復習回数'),
        ),
    ]
