# Generated by Django 3.2 on 2022-12-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_card_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='review',
            field=models.IntegerField(blank=True, null=True, verbose_name='復習回数'),
        ),
        migrations.AlterField(
            model_name='card',
            name='review_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='やり直し回数'),
        ),
    ]
