# Generated by Django 3.2 on 2022-12-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_auto_20221214_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='review',
            field=models.IntegerField(default=0, verbose_name='復習回数'),
        ),
        migrations.AlterField(
            model_name='card',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='やり直し回数'),
        ),
    ]
