# Generated by Django 3.2 on 2022-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_auto_20221218_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer_fake1',
            field=models.CharField(default='選択肢1', max_length=100, verbose_name='選択肢1'),
        ),
        migrations.AddField(
            model_name='card',
            name='answer_fake2',
            field=models.CharField(default='選択肢2', max_length=100, verbose_name='選択肢2'),
        ),
    ]
